void OP0(char *) ;
void OP0(char *) ;
void OP0(char *) ;
void OP0(char *) ;
void OP0(char *) ;
void OP0(char *) ;
void OP0(char *) ;
void OP0(char *) ;
void OP0(char *) ;
void OP1(char *) ;
void OP2(char *) ;
void OP3(char *) ;
void OP4(char *) ;
void OP5(char *) ;
void OP6(char *) ;
void OP7(char *) ;
void OP8(char *) ;
void OP9(char *) ;
void OP10(char *) ;
void OP11(char *) ;
void OP12(char *) ;
void OP13(char *) ;
void OP14(char *) ;
void OP15(char *) ;
void OP16(char *) ;
void OP17(char *) ;
void OP18(char *) ;
void OP19(char *) ;
void OP20(char *) ;
void OP21(char *) ;
void OP22(char *) ;
void OP23(char *) ;
void OP24(char *) ;
void OP25(char *) ;
void OP26(char *) ;
void OP27(char *) ;
void OP28(char *) ;
void OP29(char *) ;
void OP30(char *) ;
void OP31(char *) ;
void OP32(char *) ;
void OP33(char *, short int *) ;
void OP34(char *, short int *) ;
void OP35(char *, short int *) ;
void OP99() ;

/*Other functions*/

void printMEM() ;
void PrintLocation(int) ;
